### PR TITLE
Enable travis CI

### PR DESCRIPTION
**Pull request by johnbelamaric**

### CODE REVIEW

**Comment by johnbelamaric** [comment]
Sorry, this adds all the vendor files, which makes it easier for Travis. Now you can just do a "make test". Otherwise I have to do a "make deps" then a "make test" or I have to make deps a dependency for "test" (and "build") but then builds are slow.

**Comment by dmacthedestroyer** [comment]
no worries on the `vendor` inclusion... I've since softened my stance on it :)

**Comment by ZachEddy** [comment]
@johnbelamaric What are your thoughts on adding [repo badges](https://github.com/dwyl/repo-badges)? I'm happy to open a pull request that adds badges for test coverage and build status.

**Comment by johnbelamaric** [comment]
Thanks, just saw this. Already done...

On Mar 16, 2018, at 1:50 PM, Zach Eddy <notifications@github.com<mailto:notifications@github.com>> wrote:


@johnbelamaric<https://github.com/johnbelamaric> What are your thoughts on adding repo badges<https://github.com/dwyl/repo-badges>? I'm happy to open a pull request that adds badges for test coverage and build status.

**Pull request merged**
